---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ template "app.name" . }}-nginx-vhost
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "app.name" . }}"
data:
  default.conf:
    |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri$args $uri$args/ /index.html;
      }
    }
