version: "3"
services:
  front:
    image: node:16
    working_dir: /tmp/front/app
    volumes:
      - ../../:/tmp/front:delegated
    ports:
      - "4200:4200"
    command: >
      /bin/sh -c "npm install && npm run serve"
