export enum PSEUDO_FOLDER {
  CREATED_PERSONS = 'CREATED_PERSONS',
  REFERENCED_PERSONS = 'REFERENCED_PERSONS',
  UPDATED_INSTRUMENTS = 'UPDATED_INSTRUMENTS',
  REFERENCED_INSTRUMENTS = 'REFERENCED_INSTRUMENTS',
  ALL_FOLDERS = 'ALL_FOLDERS',
}
